---
title: "Polars, the New Gold Standard for Scikit-Learn Workflows"
subtitle: Ditch the NumPy bottleneck and build end-to-end workflows.
abstract: |
  The transition from data manipulation to machine learning has historically been a point of friction, often requiring the conversion of structured DataFrames into "anonymous" NumPy arrays.While this transition is the foundation of the scikit-learn ecosystem, it frequently results in the loss of critical metadata, specifically feature names and data types. Traditionally, Pandas has been the primary tool for managing this workflow, but as datasets grow in complexity and scale, its single-threaded nature and memory overhead have become significant bottlenecks.
  <br>
  This article explores the modern alternative: Polars. We demonstrate how the native integration between Polars and scikit-learn (introduced in version 1.4) allows data scientists to maintain a "DataFrame-in, DataFrame-out" workflow. By leveraging the transform_output="polars" configuration, practitioners can perform high-speed, multi-threaded feature engineering in Rust-backed Polars while preserving column identities through every stage of a pipeline.   
  <br>
  We provide a comparative analysis of the benefits, such as automatic horizontal concatenation (hstack) and Apache Arrow memory efficiency, alongside the limitations, including the current lack of native support for Polars LazyFrames within fit/predict cycles. Readers will learn how to build a robust, name-aware machine learning pipeline that is significantly faster and more memory-efficient than traditional Pandas-based approaches.   
author: Jesus LM
date: 2026-03-16
date-format: MMM, YYYY
format:
  html:
    toc: true
    embed-resources: true
    theme: custom.scss
    execute: true
jupyter: python3
---

# Machine Learning Workflow

## Load dataset

In [1]:
# The magic line that keeps your column names
#from sklearn import set_config
#set_config(transform_output="polars")

In [83]:
import pandas as pd
import polars as pl

df = pl.read_csv('http://bit.ly/MLtrain')
df = df.drop_nulls(subset='Embarked')
df.head()

shape: (5, 11)
┌──────────┬────────┬────────────────────────┬────────┬───┬───────────┬─────────┬───────┬──────────┐
│ Survived ┆ Pclass ┆ Name                   ┆ Sex    ┆ … ┆ Ticket    ┆ Fare    ┆ Cabin ┆ Embarked │
│ ---      ┆ ---    ┆ ---                    ┆ ---    ┆   ┆ ---       ┆ ---     ┆ ---   ┆ ---      │
│ i64      ┆ i64    ┆ str                    ┆ str    ┆   ┆ str       ┆ f64     ┆ str   ┆ str      │
╞══════════╪════════╪════════════════════════╪════════╪═══╪═══════════╪═════════╪═══════╪══════════╡
│ 0        ┆ 3      ┆ Braund, Mr. Owen       ┆ male   ┆ … ┆ A/5 21171 ┆ 7.25    ┆ null  ┆ S        │
│          ┆        ┆ Harris                 ┆        ┆   ┆           ┆         ┆       ┆          │
│ 1        ┆ 1      ┆ Cumings, Mrs. John     ┆ female ┆ … ┆ PC 17599  ┆ 71.2833 ┆ C85   ┆ C        │
│          ┆        ┆ Bradley (Fl…           ┆        ┆   ┆           ┆         ┆       ┆          │
│ 1        ┆ 3      ┆ Heikkinen, Miss. Laina ┆ female ┆ … ┆ STON/O2.  ┆ 7.925   ┆ null  ┆ S        │
│          ┆        ┆                        ┆        ┆   ┆ 3101282   ┆         ┆       ┆          │
│ 1        ┆ 1      ┆ Futrelle, Mrs. Jacques ┆ female ┆ … ┆ 113803    ┆ 53.1    ┆ C123  ┆ S        │
│          ┆        ┆ Heath (…               ┆        ┆   ┆           ┆         ┆       ┆          │
│ 0        ┆ 3      ┆ Allen, Mr. William     ┆ male   ┆ … ┆ 373450    ┆ 8.05    ┆ null  ┆ S        │
│          ┆        ┆ Henry                  ┆        ┆   ┆           ┆         ┆       ┆          │
└──────────┴────────┴────────────────────────┴────────┴───┴───────────┴─────────┴───────┴──────────┘

In [84]:
X = df.select('Parch', 'Fare')

In [85]:
y = df.get_column('Survived')

In [86]:
X.shape

(889, 2)

In [87]:
y.shape

(889,)

## Model selection

In [88]:
from sklearn.linear_model import LogisticRegression
logreg = LogisticRegression(solver='liblinear', random_state=1)

In [89]:
from sklearn.model_selection import cross_val_score
cross_val_score(logreg, X, y, cv=3, scoring='accuracy').mean()

np.float64(0.6648239148239148)

In [90]:
logreg.fit(X, y)

LogisticRegression(random_state=1, solver='liblinear')

In [91]:
df_new = pl.read_csv('http://bit.ly/MLnewdata', n_rows=10)
df_new

shape: (10, 10)
┌────────┬────────────────────────────┬────────┬──────┬───┬───────────┬─────────┬───────┬──────────┐
│ Pclass ┆ Name                       ┆ Sex    ┆ Age  ┆ … ┆ Ticket    ┆ Fare    ┆ Cabin ┆ Embarked │
│ ---    ┆ ---                        ┆ ---    ┆ ---  ┆   ┆ ---       ┆ ---     ┆ ---   ┆ ---      │
│ i64    ┆ str                        ┆ str    ┆ f64  ┆   ┆ str       ┆ f64     ┆ str   ┆ str      │
╞════════╪════════════════════════════╪════════╪══════╪═══╪═══════════╪═════════╪═══════╪══════════╡
│ 3      ┆ Kelly, Mr. James           ┆ male   ┆ 34.5 ┆ … ┆ 330911    ┆ 7.8292  ┆ null  ┆ Q        │
│ 3      ┆ Wilkes, Mrs. James (Ellen  ┆ female ┆ 47.0 ┆ … ┆ 363272    ┆ 7.0     ┆ null  ┆ S        │
│        ┆ Need…                      ┆        ┆      ┆   ┆           ┆         ┆       ┆          │
│ 2      ┆ Myles, Mr. Thomas Francis  ┆ male   ┆ 62.0 ┆ … ┆ 240276    ┆ 9.6875  ┆ null  ┆ Q        │
│ 3      ┆ Wirz, Mr. Albert           ┆ male   ┆ 27.0 ┆ … ┆ 315154    ┆ 8.6625  ┆ null  ┆ S        │
│ 3      ┆ Hirvonen, Mrs. Alexander   ┆ female ┆ 22.0 ┆ … ┆ 3101298   ┆ 12.2875 ┆ null  ┆ S        │
│        ┆ (Helg…                     ┆        ┆      ┆   ┆           ┆         ┆       ┆          │
│ 3      ┆ Svensson, Mr. Johan Cervin ┆ male   ┆ 14.0 ┆ … ┆ 7538      ┆ 9.225   ┆ null  ┆ S        │
│ 3      ┆ Connolly, Miss. Kate       ┆ female ┆ 30.0 ┆ … ┆ 330972    ┆ 7.6292  ┆ null  ┆ Q        │
│ 2      ┆ Caldwell, Mr. Albert       ┆ male   ┆ 26.0 ┆ … ┆ 248738    ┆ 29.0    ┆ null  ┆ S        │
│        ┆ Francis                    ┆        ┆      ┆   ┆           ┆         ┆       ┆          │
│ 3      ┆ Abrahim, Mrs. Joseph       ┆ female ┆ 18.0 ┆ … ┆ 2657      ┆ 7.2292  ┆ null  ┆ C        │
│        ┆ (Sophie H…                 ┆        ┆      ┆   ┆           ┆         ┆       ┆          │
│ 3      ┆ Davies, Mr. John Samuel    ┆ male   ┆ 21.0 ┆ … ┆ A/4 48871 ┆ 24.15   ┆ null  ┆ S        │
└────────┴────────────────────────────┴────────┴──────┴───┴───────────┴─────────┴───────┴──────────┘

In [92]:
X_new = df_new.select(['Parch', 'Fare'])
X_new

shape: (10, 2)
┌───────┬─────────┐
│ Parch ┆ Fare    │
│ ---   ┆ ---     │
│ i64   ┆ f64     │
╞═══════╪═════════╡
│ 0     ┆ 7.8292  │
│ 0     ┆ 7.0     │
│ 0     ┆ 9.6875  │
│ 0     ┆ 8.6625  │
│ 1     ┆ 12.2875 │
│ 0     ┆ 9.225   │
│ 0     ┆ 7.6292  │
│ 1     ┆ 29.0    │
│ 0     ┆ 7.2292  │
│ 0     ┆ 24.15   │
└───────┴─────────┘

In [93]:
logreg.predict(X_new)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [94]:
logreg.predict_proba(X_new)

array([[0.69548825, 0.30451175],
       [0.69804976, 0.30195024],
       [0.68970366, 0.31029634],
       [0.69290181, 0.30709819],
       [0.67268411, 0.32731589],
       [0.691149  , 0.308851  ],
       [0.69610719, 0.30389281],
       [0.61680219, 0.38319781],
       [0.69734295, 0.30265705],
       [0.64274043, 0.35725957]])

In [95]:
logreg.predict_proba(X_new)[:, 1]

array([0.30451175, 0.30195024, 0.31029634, 0.30709819, 0.32731589,
       0.308851  , 0.30389281, 0.38319781, 0.30265705, 0.35725957])

In [96]:
logreg.get_params()

{'C': 1.0,
 'class_weight': None,
 'dual': False,
 'fit_intercept': True,
 'intercept_scaling': 1,
 'l1_ratio': 0.0,
 'max_iter': 100,
 'n_jobs': None,
 'penalty': 'deprecated',
 'random_state': 1,
 'solver': 'liblinear',
 'tol': 0.0001,
 'verbose': 0,
 'warm_start': False}

## Encoding Categorical Features

In [97]:
from sklearn.preprocessing import OneHotEncoder
ohe = OneHotEncoder(sparse_output=False)

In [98]:
ohe.fit_transform(df.select('Embarked'))

array([[0., 0., 1.],
       [1., 0., 0.],
       [0., 0., 1.],
       ...,
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.]], shape=(889, 3))

In [99]:
ohe.categories_

[array(['C', 'Q', 'S'], dtype=object)]

In [100]:
ohe.fit_transform(df.select(['Embarked', 'Sex']))

array([[0., 0., 1., 0., 1.],
       [1., 0., 0., 1., 0.],
       [0., 0., 1., 1., 0.],
       ...,
       [0., 0., 1., 1., 0.],
       [1., 0., 0., 0., 1.],
       [0., 1., 0., 0., 1.]], shape=(889, 5))

In [101]:
ohe.categories_

[array(['C', 'Q', 'S'], dtype=object), array(['female', 'male'], dtype=object)]

## ColumnTransformer and Pipeline

In [102]:
cols = ['Parch', 'Fare', 'Embarked', 'Sex']
X = df.select(cols)

In [103]:
X

shape: (889, 4)
┌───────┬─────────┬──────────┬────────┐
│ Parch ┆ Fare    ┆ Embarked ┆ Sex    │
│ ---   ┆ ---     ┆ ---      ┆ ---    │
│ i64   ┆ f64     ┆ str      ┆ str    │
╞═══════╪═════════╪══════════╪════════╡
│ 0     ┆ 7.25    ┆ S        ┆ male   │
│ 0     ┆ 71.2833 ┆ C        ┆ female │
│ 0     ┆ 7.925   ┆ S        ┆ female │
│ 0     ┆ 53.1    ┆ S        ┆ female │
│ 0     ┆ 8.05    ┆ S        ┆ male   │
│ …     ┆ …       ┆ …        ┆ …      │
│ 0     ┆ 13.0    ┆ S        ┆ male   │
│ 0     ┆ 30.0    ┆ S        ┆ female │
│ 2     ┆ 23.45   ┆ S        ┆ female │
│ 0     ┆ 30.0    ┆ C        ┆ male   │
│ 0     ┆ 7.75    ┆ Q        ┆ male   │
└───────┴─────────┴──────────┴────────┘

In [104]:
ohe = OneHotEncoder()

In [105]:
from sklearn.compose import make_column_transformer

ct = make_column_transformer(
    (ohe, ['Embarked', 'Sex']),
    remainder='drop')

In [106]:
ct.fit_transform(X)

array([[0., 0., 1., 0., 1.],
       [1., 0., 0., 1., 0.],
       [0., 0., 1., 1., 0.],
       ...,
       [0., 0., 1., 1., 0.],
       [1., 0., 0., 0., 1.],
       [0., 1., 0., 0., 1.]], shape=(889, 5))

In [107]:
ct = make_column_transformer(
    (ohe, ['Embarked', 'Sex']),
    remainder='passthrough')

In [108]:
ct.fit_transform(X)

array([[ 0.    ,  0.    ,  1.    , ...,  1.    ,  0.    ,  7.25  ],
       [ 1.    ,  0.    ,  0.    , ...,  0.    ,  0.    , 71.2833],
       [ 0.    ,  0.    ,  1.    , ...,  0.    ,  0.    ,  7.925 ],
       ...,
       [ 0.    ,  0.    ,  1.    , ...,  0.    ,  2.    , 23.45  ],
       [ 1.    ,  0.    ,  0.    , ...,  1.    ,  0.    , 30.    ],
       [ 0.    ,  1.    ,  0.    , ...,  1.    ,  0.    ,  7.75  ]],
      shape=(889, 7))

In [109]:
ct.get_feature_names_out()

array(['onehotencoder__Embarked_C', 'onehotencoder__Embarked_Q',
       'onehotencoder__Embarked_S', 'onehotencoder__Sex_female',
       'onehotencoder__Sex_male', 'remainder__Parch', 'remainder__Fare'],
      dtype=object)

In [110]:
ct = make_column_transformer(
    (ohe, ['Embarked', 'Sex']),
    ('passthrough', ['Parch', 'Fare']))

In [111]:
ct.fit_transform(X)

array([[ 0.    ,  0.    ,  1.    , ...,  1.    ,  0.    ,  7.25  ],
       [ 1.    ,  0.    ,  0.    , ...,  0.    ,  0.    , 71.2833],
       [ 0.    ,  0.    ,  1.    , ...,  0.    ,  0.    ,  7.925 ],
       ...,
       [ 0.    ,  0.    ,  1.    , ...,  0.    ,  2.    , 23.45  ],
       [ 1.    ,  0.    ,  0.    , ...,  1.    ,  0.    , 30.    ],
       [ 0.    ,  1.    ,  0.    , ...,  1.    ,  0.    ,  7.75  ]],
      shape=(889, 7))

## Pipeline chaining

In [112]:
from sklearn.pipeline import make_pipeline
pipe = make_pipeline(ct, logreg)

In [113]:
pipe.fit(X, y)

Pipeline(steps=[('columntransformer',
                 ColumnTransformer(transformers=[('onehotencoder',
                                                  OneHotEncoder(),
                                                  ['Embarked', 'Sex']),
                                                 ('passthrough', 'passthrough',
                                                  ['Parch', 'Fare'])])),
                ('logisticregression',
                 LogisticRegression(random_state=1, solver='liblinear'))])

In [114]:
X_t = ct.fit_transform(X)
logreg.fit(X_t, y)

LogisticRegression(random_state=1, solver='liblinear')

In [115]:
print(X.shape)
print(X_t.shape)

(889, 4)
(889, 7)

In [118]:
data_new = {
    "Parch": [0, 0, 0, 0, 1, 0, 0, 1, 0, 0],
    "Fare": [7.8292, 7.0000, 9.6875, 8.6625, 12.2875, 9.2250, 7.6292, 29.0000, 7.2292, 24.1500],
    "Embarked": ["Q", "S", "Q", "S", "S", "S", "Q", "S", "C", "S"],
    "Sex": ["male", "female", "male", "male", "female", "male", "female", "male", "female", "male"]
}

X_new = pl.DataFrame(data_new)

In [119]:
pipe.predict(X_new)

array([0, 1, 0, 0, 1, 0, 1, 0, 1, 0])

In [120]:
X_new_t = ct.transform(X_new)
logreg.predict(X_new_t)

array([0, 1, 0, 0, 1, 0, 1, 0, 1, 0])

In [121]:
print(X_new.shape)
print(X_new_t.shape)

(10, 4)
(10, 7)

In [122]:
ct = make_column_transformer(
    (ohe, ['Embarked', 'Sex']),
    ('drop', ['Fare']),
    remainder='passthrough')
ct.fit_transform(X)

array([[0., 0., 1., 0., 1., 0.],
       [1., 0., 0., 1., 0., 0.],
       [0., 0., 1., 1., 0., 0.],
       ...,
       [0., 0., 1., 1., 0., 2.],
       [1., 0., 0., 0., 1., 0.],
       [0., 1., 0., 0., 1., 0.]], shape=(889, 6))

In [123]:
ct = make_column_transformer(
    (ohe, ['Embarked', 'Sex']),
    ('passthrough', ['Parch']),
    remainder='drop')
ct.fit_transform(X)

array([[0., 0., 1., 0., 1., 0.],
       [1., 0., 0., 1., 0., 0.],
       [0., 0., 1., 1., 0., 0.],
       ...,
       [0., 0., 1., 1., 0., 2.],
       [1., 0., 0., 0., 1., 0.],
       [0., 1., 0., 0., 1., 0.]], shape=(889, 6))

# Contact